show:
  world: tagiaomc
  x: 0
  y: 80
  z: 0

timeline:
  dragon: 120
  lion: 100
  horse: 80
  text: 120
  finale: 240

firework:
  radius: 16
  height_min: 4
  height_max: 12
  normal_interval: 5
  ring_interval: 20
