show:
  world: tagiaomc
  x: 0
  y: 100
  z: 0

firework:
  enabled: true
  duration: 300
  interval: 6
  radius: 25
  height: 20
  amount: 16
  types: ALL
  colors: RAINBOW
  pattern: CIRCLE

text:
  enabled: true
  value: "TA GIAO"
  size: 1
  height: 18
  color: RED
